import otherImage1 from 'assets/img/sedcard/otherImage1.jpg';
import otherImage2 from 'assets/img/sedcard/otherImage2.jpg';
import otherImage3 from 'assets/img/sedcard/otherImage3.jpg';
import otherImage4 from 'assets/img/sedcard/otherImage4.jpg';
import otherImage5 from 'assets/img/sedcard/otherImage5.jpg';
import otherImage6 from 'assets/img/sedcard/otherImage6.jpg';
import otherImage7 from 'assets/img/sedcard/otherImage7.jpg';
import otherImage8 from 'assets/img/sedcard/otherImage8.jpg';

const dummyListNothingFound = [
  {
    path: otherImage1,
    name: 'Annija Abzalone',
    job: 'Photographer',
    jobType: 'photo',
    address: 'Cēsis, Cēsu pilsēta, Latvia',
    location: ['Latvia'],
    followers: 11,
    expertise: 'professional',
    studio: 'professional',
    postproduction: 'professional',
    videography: 'professional',
    description: 'Conceptual & Advertising | Food & Still Life',
    href: '/artbuyer/creator-profile',
    tags: ['photographer', 'fashion'],
  },
  {
    path: otherImage2,
    name: 'Christian Burmester',
    job: 'Model',
    jobType: 'model',
    address: 'Bremen, Germany',
    location: ['Bremen', 'Germany'],
    followers: 21,
    expertise: 'professional',
    studio: 'professional',
    postproduction: 'professional',
    videography: 'professional',
    description:
      'Conceptual & Advertising | Architecture & Interior | People & Lifestyle',
    href: '/artbuyer/creator-profile',
    tags: ['pretty', 'fashion'],
  },
  {
    path: otherImage3,
    name: 'Lorenzo  Ilie',
    job: 'MakeUp Artist',
    jobType: 'makeUp',
    address: 'Madrid, Spain',
    location: ['Madrid', 'Spain'],
    followers: 31,
    expertise: 'professional',
    studio: 'professional',
    postproduction: 'professional',
    videography: 'professional',
    description: 'Fine Arts | People & Lifestyle | Fashion & Beauty',
    href: '/artbuyer/creator-profile',
    tags: ['person', 'studio'],
  },
  {
    path: otherImage4,
    name: 'Francesco Guerra',
    job: 'Photographer',
    jobType: 'photo',
    address: 'Napoli, Metropolitan City of Naples, Italy',
    location: ['Napoli', 'Italy'],
    followers: 41,
    expertise: 'professional',
    studio: 'professional',
    postproduction: 'professional',
    videography: 'professional',
    description: 'Sports & Cars | People & Lifestyle | Editorial & Documentary',
    href: '/artbuyer/creator-profile',
    tags: ['photographer', 'fashion', 'portrait'],
  },
  {
    path: otherImage5,
    name: 'Dimitri  Reimer',
    job: 'Model',
    jobType: 'model',
    address: 'Augsburg, Germany',
    location: ['Augsburg', 'Germany'],
    followers: 51,
    expertise: 'upAndComing',
    studio: 'upAndComing',
    postproduction: 'upAndComing',
    videography: 'upAndComing',
    description:
      'Editorial & Documentary | Business & Corporate | People & Lifestyle',
    href: '/artbuyer/creator-profile',
    tags: ['beach', 'fashion', 'pretty'],
  },
  {
    path: otherImage6,
    name: 'Ivan Stamato Baptista',
    job: 'Photographer',
    jobType: 'photo',
    address: 'Porto, Portugal',
    location: ['Porto', 'Portugal'],
    followers: 61,
    expertise: 'upAndComing',
    studio: 'upAndComing',
    postproduction: 'upAndComing',
    videography: 'upAndComing',
    description: 'Fashion & Beauty | People & Lifestyle',
    href: '/artbuyer/creator-profile',
    tags: ['photo', 'fashion'],
  },
  {
    path: otherImage7,
    name: 'Leyna Amly',
    job: 'Photographer',
    jobType: 'photo',
    address: 'Barcelona, Spain',
    location: ['Barcelona', 'Spain'],
    followers: 71,
    expertise: 'upAndComing',
    studio: 'upAndComing',
    postproduction: 'upAndComing',
    videography: 'upAndComing',
    description: 'People & Lifestyle | Editorial & Documentary',
    href: '/artbuyer/creator-profile',
    tags: ['photo', 'fashion'],
  },
  {
    path: otherImage8,
    name: 'Rosemary Osuya',
    job: 'Photographer',
    jobType: 'photo',
    address: 'Paris, France',
    location: ['Paris', 'France'],
    followers: 81,
    expertise: 'upAndComing',
    studio: 'upAndComing',
    postproduction: 'upAndComing',
    videography: 'upAndComing',
    description: 'Conceptual & Advertising | Fashion & Beauty',
    href: '/artbuyer/creator-profile',
    tags: ['person', 'photographer'],
  },
];

export default dummyListNothingFound;
