import img1 from './gallery/gallery_1.jpg';
import img2 from './gallery/gallery_2.jpg';
import img3 from './gallery/gallery_3.jpg';
import img4 from './gallery/gallery_4.jpg';
import img5 from './gallery/gallery_5.jpg';
import img6 from './gallery/gallery_6.jpg';
import img7 from './gallery/gallery_7.jpg';
import img8 from './gallery/gallery_8.jpg';

const dummyCreatorsListForCreators = [
  {
    path: img1,
    name: 'Annija Abzalone',
    job: 'Photographer',
    jobType: 'photo',
    address: 'Cēsis, Cēsu pilsēta, Latvia',
    location: ['Latvia'],
    followers: 11,
    expertise: 'professional',
    studio: 'professional',
    postproduction: 'professional',
    videography: 'professional',
    description: 'Conceptual & Advertising | Food & Still Life',
    href: '/creator/other-profile',
    tags: ['photographer', 'fashion'],
  },
  {
    path: img2,
    name: 'Christian Burmester',
    job: 'Model',
    jobType: 'model',
    address: 'Bremen, Germany',
    location: ['Bremen', 'Germany'],
    followers: 21,
    expertise: 'professional',
    studio: 'professional',
    postproduction: 'professional',
    videography: 'professional',
    description:
      'Conceptual & Advertising | Architecture & Interior | People & Lifestyle',
    href: '/creator/other-profile',
    tags: ['pretty', 'fashion'],
  },
  {
    path: img3,
    name: 'Lorenzo  Ilie',
    job: 'MakeUp Artist',
    jobType: 'makeUp',
    address: 'Madrid, Spain',
    location: ['Madrid', 'Spain'],
    followers: 31,
    expertise: 'professional',
    studio: 'professional',
    postproduction: 'professional',
    videography: 'professional',
    description: 'Fine Arts | People & Lifestyle | Fashion & Beauty',
    href: '/creator/other-profile',
    tags: ['person', 'studio'],
  },
  {
    path: img4,
    name: 'Francesco Guerra',
    job: 'Photographer',
    jobType: 'photo',
    address: 'Napoli, Metropolitan City of Naples, Italy',
    location: ['Napoli', 'Italy'],
    followers: 41,
    expertise: 'professional',
    studio: 'professional',
    postproduction: 'professional',
    videography: 'professional',
    description: 'Sports & Cars | People & Lifestyle | Editorial & Documentary',
    href: '/creator/other-profile',
    tags: ['photographer', 'fashion', 'portrait'],
  },
  {
    path: img5,
    name: 'Dimitri  Reimer',
    job: 'Model',
    jobType: 'model',
    address: 'Augsburg, Germany',
    location: ['Augsburg', 'Germany'],
    followers: 51,
    expertise: 'upAndComing',
    studio: 'upAndComing',
    postproduction: 'upAndComing',
    videography: 'upAndComing',
    description:
      'Editorial & Documentary | Business & Corporate | People & Lifestyle',
    href: '/creator/other-profile',
    tags: ['beach', 'fashion', 'pretty'],
  },
  {
    path: img6,
    name: 'Ivan Stamato Baptista',
    job: 'Photographer',
    jobType: 'photo',
    address: 'Porto, Portugal',
    location: ['Porto', 'Portugal'],
    followers: 61,
    expertise: 'upAndComing',
    studio: 'upAndComing',
    postproduction: 'upAndComing',
    videography: 'upAndComing',
    description: 'Fashion & Beauty | People & Lifestyle',
    href: '/creator/other-profile',
    tags: ['photo', 'fashion'],
  },
  {
    path: img7,
    name: 'Leyna Amly',
    job: 'Photographer',
    jobType: 'photo',
    address: 'Barcelona, Spain',
    location: ['Barcelona', 'Spain'],
    followers: 71,
    expertise: 'upAndComing',
    studio: 'upAndComing',
    postproduction: 'upAndComing',
    videography: 'upAndComing',
    description: 'People & Lifestyle | Editorial & Documentary',
    href: '/creator/other-profile',
    tags: ['photo', 'fashion'],
  },
  {
    path: img8,
    name: 'Rosemary Osuya',
    job: 'Photographer',
    jobType: 'photo',
    address: 'Paris, France',
    location: ['Paris', 'France'],
    followers: 81,
    expertise: 'upAndComing',
    studio: 'upAndComing',
    postproduction: 'upAndComing',
    videography: 'upAndComing',
    description: 'Conceptual & Advertising | Fashion & Beauty',
    href: '/creator/other-profile',
    tags: ['person', 'photographer'],
  },
];

export default dummyCreatorsListForCreators;
