import image1 from "assets/img/sedcard/image1.jpg";
import image2 from "assets/img/sedcard/image2.jpg";
import image3 from "assets/img/sedcard/image3.jpg";
import image4 from "assets/img/sedcard/image4.jpg";
import image5 from "assets/img/sedcard/image5.jpg";
import image6 from "assets/img/sedcard/image6.jpg";
import image7 from "assets/img/sedcard/image7.jpg";
import image8 from "assets/img/sedcard/image8.jpg";

const dummyImagesArtbuyer = [
  {
    img: image1,
    inSedcard: true,
    isCoverImage: true,
    camera: "NIKON D5500",
    aperture: "f/7.1",
    iso: "250",
    orientation: "Landscape",
    imageFile: "lowRes",
    pricing: "rightsReady",
    isLiked: false,
    numberOfLikes: 54,
    tags: [
      "photographer",
      "ocean",
      "beach",
      "person",
      "summer",
      "water",
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: image2,
    inSedcard: true,
    isCoverImage: false,
    camera: "CANON E5500",
    aperture: "f/3.1",
    iso: "120",
    orientation: "Portrait",
    imageFile: "highRes",
    pricing: "uponRequest",
    isLiked: true,
    numberOfLikes: 32,
    tags: [
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: image3,
    inSedcard: true,
    isCoverImage: false,
    camera: "NIKON D5500",
    aperture: "f/7.1",
    iso: "250",
    orientation: "Landscape",
    imageFile: "lowRes",
    pricing: "rightsReady",
    isLiked: false,
    numberOfLikes: 54,
    tags: [
      "photographer",
      "ocean",
      "beach",
      "person",
      "summer",
      "water",
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: image4,
    inSedcard: true,
    isCoverImage: false,
    camera: "CANON E5500",
    aperture: "f/3.1",
    iso: "120",
    orientation: "Portrait",
    imageFile: "highRes",
    pricing: "uponRequest",
    isLiked: true,
    numberOfLikes: 32,
    tags: [
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: image5,
    inSedcard: false,
    isCoverImage: false,
    camera: "NIKON D5500",
    aperture: "f/7.1",
    iso: "250",
    orientation: "Landscape",
    imageFile: "lowRes",
    pricing: "rightsReady",
    isLiked: false,
    numberOfLikes: 54,
    tags: [
      "photographer",
      "ocean",
      "beach",
      "person",
      "summer",
      "water",
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: image6,
    inSedcard: false,
    isCoverImage: false,
    camera: "CANON E5500",
    aperture: "f/3.1",
    iso: "120",
    orientation: "Portrait",
    imageFile: "highRes",
    pricing: "uponRequest",
    isLiked: true,
    numberOfLikes: 32,
    tags: [
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: image7,
    inSedcard: false,
    isCoverImage: false,
    camera: "NIKON D5500",
    aperture: "f/7.1",
    iso: "250",
    orientation: "Landscape",
    imageFile: "lowRes",
    pricing: "rightsReady",
    isLiked: false,
    numberOfLikes: 54,
    tags: [
      "photographer",
      "ocean",
      "beach",
      "person",
      "summer",
      "water",
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: image8,
    inSedcard: false,
    isCoverImage: false,
    camera: "CANON E5500",
    aperture: "f/3.1",
    iso: "120",
    orientation: "Portrait",
    imageFile: "highRes",
    pricing: "uponRequest",
    isLiked: true,
    numberOfLikes: 32,
    tags: [
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
];

export { dummyImagesArtbuyer };
