import otherImage1 from "assets/img/sedcard/otherImage1.jpg";
import otherImage2 from "assets/img/sedcard/otherImage2.jpg";
import otherImage3 from "assets/img/sedcard/otherImage3.jpg";
import otherImage4 from "assets/img/sedcard/otherImage4.jpg";
import otherImage5 from "assets/img/sedcard/otherImage5.jpg";
import otherImage6 from "assets/img/sedcard/otherImage6.jpg";
import otherImage7 from "assets/img/sedcard/otherImage7.jpg";
import otherImage8 from "assets/img/sedcard/otherImage8.jpg";
import otherImage9 from "assets/img/sedcard/otherImage9.jpg";
import otherImage10 from "assets/img/sedcard/otherImage10.jpg";
import otherImage11 from "assets/img/sedcard/otherImage11.jpg";
import otherImage12 from "assets/img/sedcard/otherImage12.jpg";

const dummyOtherProfileImagesFileInfo = [
  {
    img: otherImage1,
    camera: "NIKON D5500",
    aperture: "f/7.1",
    iso: "250",
    orientation: "Landscape",
    imageFile: "lowRes",
    pricing: "rightsReady",
    isLiked: false,
    numberOfLikes: 54,
    tags: [
      "photographer",
      "ocean",
      "beach",
      "person",
      "summer",
      "water",
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage2,
    camera: "CANON E5500",
    aperture: "f/3.1",
    iso: "250",
    orientation: "Portrait",
    imageFile: "highRes",
    pricing: "uponRequest",
    isLiked: true,
    numberOfLikes: 32,
    tags: [
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage3,
    camera: "NIKON D5500",
    aperture: "f/7.1",
    iso: "250",
    orientation: "Landscape",
    imageFile: "lowRes",
    pricing: "rightsReady",
    isLiked: false,
    numberOfLikes: 54,
    tags: [
      "photographer",
      "ocean",
      "beach",
      "person",
      "summer",
      "water",
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage4,
    camera: "CANON E5500",
    aperture: "f/3.1",
    iso: "120",
    orientation: "Portrait",
    imageFile: "highRes",
    pricing: "uponRequest",
    isLiked: true,
    numberOfLikes: 32,
    tags: [
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage5,
    camera: "NIKON D5500",
    aperture: "f/7.1",
    iso: "250",
    orientation: "Landscape",
    imageFile: "lowRes",
    pricing: "rightsReady",
    isLiked: false,
    numberOfLikes: 54,
    tags: [
      "photographer",
      "ocean",
      "beach",
      "person",
      "summer",
      "water",
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage6,
    camera: "CANON E5500",
    aperture: "f/3.1",
    iso: "120",
    orientation: "Portrait",
    imageFile: "highRes",
    pricing: "uponRequest",
    isLiked: true,
    numberOfLikes: 32,
    tags: [
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage7,
    camera: "NIKON D5500",
    aperture: "f/7.1",
    iso: "250",
    orientation: "Landscape",
    imageFile: "lowRes",
    pricing: "rightsReady",
    isLiked: false,
    numberOfLikes: 54,
    tags: [
      "photographer",
      "ocean",
      "beach",
      "person",
      "summer",
      "water",
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage8,
    camera: "CANON E5500",
    aperture: "f/3.1",
    iso: "120",
    orientation: "Portrait",
    imageFile: "highRes",
    pricing: "uponRequest",
    isLiked: true,
    numberOfLikes: 32,
    tags: [
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage9,
    camera: "NIKON D5500",
    aperture: "f/7.1",
    iso: "250",
    orientation: "Landscape",
    imageFile: "lowRes",
    pricing: "rightsReady",
    isLiked: false,
    numberOfLikes: 54,
    tags: [
      "photographer",
      "ocean",
      "beach",
      "person",
      "summer",
      "water",
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage10,
    camera: "CANON E5500",
    aperture: "f/3.1",
    iso: "120",
    orientation: "Portrait",
    imageFile: "highRes",
    pricing: "uponRequest",
    isLiked: true,
    numberOfLikes: 32,
    tags: [
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage11,
    camera: "NIKON D5500",
    aperture: "f/7.1",
    iso: "250",
    orientation: "Landscape",
    imageFile: "lowRes",
    pricing: "rightsReady",
    isLiked: false,
    numberOfLikes: 54,
    tags: [
      "photographer",
      "ocean",
      "beach",
      "person",
      "summer",
      "water",
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
  {
    img: otherImage12,
    camera: "CANON E5500",
    aperture: "f/3.1",
    iso: "120",
    orientation: "Portrait",
    imageFile: "highRes",
    pricing: "uponRequest",
    isLiked: true,
    numberOfLikes: 32,
    tags: [
      "clothing",
      "sky",
      "fashion",
      "pretty",
      "studio",
      "travel",
      "portrait",
    ],
  },
];

export { dummyOtherProfileImagesFileInfo };
